[package]
name = "cli"
version.workspace = true
edition.workspace = true
description = "Command-line interface for haucet"
license.workspace = true

[[bin]]
name = "haucet"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
common = { path = "../tools-common" }
hm-fastboot = { path = "../hm-fastboot" }
hisi-vcom = { path = "../hisi-vcom" }
tokio = { version = "1", features = ["rt-multi-thread"] }

[build-dependencies]
winresource = { version = "0.1", default-features = false }
